config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength

Rails.application.routes.draw do
  root 'sessions#new'
  get '/dashboard', to: 'homes#welcome'
  get '/profile', to: 'homes#profile'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  delete '/logout', to: 'sessions#destroy'
  get '/authenticate', to: 'sessions#authenticate'
  get '/categories/fetch', to: 'categories#fetch_data'
  patch '/notifications/mark_read', to: 'notification#mark_read'
  patch '/notifications/mark/:id', to: 'notification#mark', as: :notifications_mark

  resources :users do
    collection do
      get :search
    end
  end
  resources :brands do
    collection do
      get :search
    end
  end
  resources :categories do
    collection do
      get :search
      get :storage
    end
  end
  resources :issues, except: %i[destroy edit] do
    collection do
      get :search
    end
  end
  resources :items do
    collection do
      get :search
      post :clear_filter
    end
  end
  resources :notification
  match '*unmatched', to: 'application#not_found_method', via: :all,
                      constraints: lambda { |req|
                                     !req.path.match(%r{\A/rails/active_storage/})
                                   }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

# rubocop:enable Metrics/BlockLength

app/views/partials/_brands.html.erb
<thead>
  <tr class="text-center">
    <%= render 'partials/sort', sort: sort %>
    <%= render 'partials/sort_created', sort: sort %>
    <th scope="col">Actions</th>
  </tr>
</thead>

app/views/partials/_categories.html.erb
<thead>
  <tr class="text-center">
    <%= render 'partials/sort', sort: sort %>
    <th scope="col">Required Quantity</th>
    <th scope="col">Buffer Quantity</th>
    <th scope="col">Expected Buffer</th>
    <th scope="col">Priority</th>
    <%= render 'partials/sort_created', sort: sort %>
    <th scope="col">Actions</th>
  </tr>
</thead>

app/views/partials/_clear_filter.html.erb
<%= form_tag(search_items_path, method: "get") do %>
    <div class="col-md-1 align-self-end">
      <div class="form-group">
        <%= submit_tag "Clear Filter", class: "btn btn-primary" %>
      </div>
    </div>
  <%= hidden_field_tag :filter, true %>
<% end %>

app/views/partials/_dashboard.html.erb
<table class="table table-bordered">
  <thead>
    <tr class="table-primary">
      <th scope="col">Id</th>
      <th scope="col">Name</th>
      <% if limit == 0 %>
        <th scope="col">Actions</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
  <% if limit == 0 %>
    <% type.all.each do |type_name| %>
      <tr class="table-info">
        <td><%= type_name.id %></td>
        <% if type == Issue %>
          <td><%= type_name.description %></td>
        <% else %>
          <td><%= type_name.name %></td>
        <% end %>
        <td>
          <%= link_to "Edit", send("edit_#{type_name.class.to_s.downcase}_path", type_name), class: 'btn btn-warning' %>
          <%= link_to "Delete", send("#{type_name.class.to_s.downcase}_path", type_name), method: :delete, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  <% else %>
    <% type.limit(limit).each do |type_name| %>
      <tr class="table-info">
        <td><%= type_name.id %></td>
        <% if type == Issue %>
          <td><%= type_name.description %></td>
        <% else %>
          <td><%= type_name.name %></td>
        <% end %>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

app/views/partials/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= flash[:alert] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/partials/_items.html.erb
<thead>
  <tr class="text-center">
    <%= render 'partials/user_items', sort: sort %>
  </tr>
</thead>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <div class="container">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% if current_user %>
      <%= link_to "InventoryManagement", dashboard_path, class: 'navbar-brand' %>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Profile", profile_path, class: 'nav-link' %>
          </li>
          <% if authenticate_user %>
          <li class="nav-item">
            <%= link_to "Users", users_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Brands", brands_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Categories",  categories_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Items", items_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Issues", issues_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Storage", storage_categories_path, class: 'nav-link' %>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "Items", items_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Issues", issues_path, class: 'nav-link' %>
          </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "Logout", logout_path, method: :delete, class: 'nav-link' %>
          </li>
        </ul>
      </div>
      <div class="dropdown">
        <a class="btn dropdown-toggle text-dark" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="modal" data-bs-target="#notificationModal" aria-expanded="false">
          <i class="fa-regular fa-bell text-dark"></i>
          <span class="badge bg-danger" id="notificationCounter"><%= Notification.unread(current_user).count %></span>
        </a>
        <!-- Modal -->
        <div class="modal fade" id="notificationModal" tabindex="-1" aria-labelledby="notificationModalLabel" aria-hidden="true">
         <div class="modal-dialog modal-dialog-top-right">
           <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="notificationModalLabel">Notifications</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body" id="modalBody">
                <% Notification.unread(current_user).reverse_each do |notification| %>
                  <div class="notification-item" id="notification-<%= notification.id %>">
                    <div class="row notification-priority-<%= notification.priority %>" >
                      <div class="col-10">
                        <div class="notification-content">
                          <p class="notification-text"><%= notification.message %></p>
                          <small class="text-muted">Sent on <%= notification.created_at.strftime('%B %d, %Y at %H:%M') %></small><br>
                          <button class="btn btn-sm add-btn mark-read-button" id="mark_<%= notification.id %>" data-notification_id="<%= notification.id %>">
                            <i class="fa-solid fa-check"></i> Mark read
                          </button>
                        </div>
                      </div>
                    <hr>
                    </div>
                  </div>
                <% end %>
              </div>
              <div class="modal-footer">
               <%= button_to notifications_mark_read_path, remote: true, method: :patch, class: 'btn btn-sm add-btn', id: 'markAllReadButton' do %>
                <i class="fa-solid fa-check-double"></i>Mark all read
               <% end %>
              </div>
           </div>
         </div>
        </div> 
      </div>
    <% else %>
      <%= link_to "InventoryManagement", login_path, class: 'navbar-brand' %>
    <% end %> 
  </div>
</nav>

app/views/partials/_paginate.html.erb
<div class="text-center mt-3 mb-3">
  <nav>
    <ul class="pagination justify-content-center">
      <%= paginate obj %>
    </ul>
  </nav>
</div>

app/views/partials/_search.html.erb
<div class="col-md-3">
  <%= form_for :search_category, url: search, method: :get do |form| %>
    <div class="input-group">
      <% previous_search = session[:query].presence %>
      <%= form.text_field :query, value: previous_search, class: "form-control form-control-sm " ,placeholder: 'Search' %>
      <div class="input-group-append">
        <%= form.button :submit, class: "btn btn-primary btn-sm" do %>
          <i class="fas fa-search fa-sm"></i>
        <% end %>         
      </div>
    </div>
  <% end %>
</div>
  

app/views/partials/_sort.html.erb
<th scope="col">Name 
  <%= link_to url: sort, sort_by: "name_asc" do %>
    <% image_tag "up.png", class: "sort-icon" %>
  <% end %>
  <%= link_to url: sort, sort_by: "name_desc" do %>
    <% image_tag "down.png", class: "sort-icon" %>
  <% end %>
</th>

app/views/partials/_sort_created.html.erb
<th scope="col">Created At 
  <%= link_to url: sort, sort_by: "time_asc" do %>
    <% image_tag "up.png", class: "sort-icon" %>
  <% end %>
  <%= link_to url: sort, sort_by: "time_desc" do %>
    <% image_tag "down.png", class: "sort-icon" %>
  <% end %>
</th>

app/views/partials/_user_items.html.erb
<th scope="col">Id
  <%= link_to url: sort, sort_by: "uid_asc" do %>
    <% image_tag "up.png", class: "sort-icon" %>
  <% end %>
  <%= link_to url: sort, sort_by: "uid_desc" do %>
    <% image_tag "down.png", class: "sort-icon" %>
  <% end %>
</th>
<th scope="col">Name 
  <%= link_to url: sort, sort_by: "name_asc" do %>
    <% image_tag "up.png", class: "sort-icon" %>
  <% end %>
  <%= link_to url: sort, sort_by: "name_desc" do %>
    <% image_tag "down.png", class: "sort-icon" %>
  <% end %>
</th>
<th scope="col">
  <div class="d-flex align-items-center justify-content-center">
    <div class="mr-2">
      Brand Name
    </div>
    <div class="btn-group d-flex">
      <%= link_to url: sort, sort_by: "brand_asc" do %>
        <% image_tag "up.png", class: "sort-icon" %>
      <% end %>
      <%= link_to url: sort, sort_by: "brand_desc" do %>
        <% image_tag "down.png", class: "sort-icon" %>
      <% end %>
    </div>
  </div>
</th>
<th scope="col">
  <div class="d-flex align-items-center justify-content-center">
    <div class="mr-2">
      Category Name
    </div>
    <div class="btn-group d-flex">
      <%= link_to url: sort, sort_by: "category_asc" do %>
        <% image_tag "up.png", class: "sort-icon" %>
      <% end %>
      <%= link_to url: sort, sort_by: "category_desc" do %>
        <% image_tag "down.png", class: "sort-icon" %>
      <% end %>
    </div>
  </div>
</th>
<th scope="col">Status</th>
<%= render 'partials/sort_created', sort: sort %>
<th scope="col">Actions</th>