config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength

Rails.application.routes.draw do
  root 'sessions#new'
  get '/dashboard', to: 'homes#welcome'
  get '/profile', to: 'homes#profile'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  delete '/logout', to: 'sessions#destroy'
  get '/authenticate', to: 'sessions#authenticate'
  get '/categories/fetch', to: 'categories#fetch_data'
  patch '/notifications/mark_read', to: 'notification#mark_read'
  patch '/notifications/mark/:id', to: 'notification#mark', as: :notifications_mark

  resources :users do
    collection do
      get :search
    end
  end
  resources :brands do
    collection do
      get :search
    end
  end
  resources :categories do
    collection do
      get :search
      get :storage
    end
  end
  resources :issues, except: %i[destroy edit] do
    collection do
      get :search
    end
  end
  resources :items do
    collection do
      get :search
      post :clear_filter
    end
  end
  resources :notification
  match '*unmatched', to: 'application#not_found_method', via: :all,
                      constraints: lambda { |req|
                                     !req.path.match(%r{\A/rails/active_storage/})
                                   }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

# rubocop:enable Metrics/BlockLength

app/models/item.rb
# frozen_string_literal: true

# this is the Item model
class Item < ApplicationRecord
  include Searchable
  belongs_to :user, optional: true
  belongs_to :brand
  belongs_to :category
  has_many :issues, dependent: :destroy
  has_many_attached :documents, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
  validates :notes, length: { maximum: 100 }
  validates :category_id, presence: true
  validates :brand_id, presence: true
  validates :documents,
            content_type: {
              in: ['image/png', 'image/jpeg', 'application/pdf', 'application/msword', 'text/plain'],
              message: 'File must be of type png, jpeg, pdf, doc or txt'
            },
            size: {
              less_than: 5.megabytes,
              message: 'File size should be less than 5 MB'
            }
  validate :validate_user_id_exists, if: -> { user_id.present? }

  def validate_user_id_exists
    return if User.exists?(user_id)

    errors.add(:user_id, 'is not a valid user')
  end

  def self.index_data
    __elasticsearch__.create_index! force: true
    __elasticsearch__.import
  end

  settings do
    mappings dynamic: 'true' do
      indexes :name, type: :text
      indexes :uid, type: :keyword
      indexes :user_name, type: :text
      indexes :brand_name, type: :text
      indexes :category_name, type: :text
      indexes :brand_name, type: :text
    end
  end
  # rubocop:disable Metrics/Style/HashSyntax
  # rubocop:disable Metrics/MethodLength

  def as_indexed_json(_options = {})
    {
      uid: uid,
      name: name,
      notes: notes,
      status: status,
      user_id: user&.id,
      user_name: user&.name,
      category_id: category.id,
      category_name: category.name,
      brand_name: brand.name,
      brand_id: brand.id
    }
  end

  # rubocop:enable Metrics/Style/HashSyntax
  def self.search_result(query)
    search({
             "query": {
               "bool": {
                 "should": [
                   {
                     "query_string": {
                       "query": "#{query}*",
                       "fields": %w[name notes user_name category_name brand_name],
                       "default_operator": 'AND'
                     }
                   },
                   {
                     "multi_match": {
                       "query": query,
                       "fields": ['uid'],
                       "operator": 'or'
                     }
                   }
                 ]
               }
             }
           })
  end
  # rubocop:enable Metrics/MethodLength
  index_data
end

app/controllers/items_controller.rb
# frozen_string_literal: true

# this is the Items controller
class ItemsController < ApplicationController
  include ItemsHelper
  before_action :current_user?
  before_action :admin?, except: %i[index show search]
  before_action :fetch_item, only: %i[show edit update destroy]
  before_action :check_show, only: %i[show]
  def index
    initialize_session
    session[:query] = nil
    @items = if authenticate_user
               Item.includes(:brand, :category, :user).all
             else
               current_user.items.includes(:brand, :category)
             end
    sort_param = params[:sort_by]
    @items = sort_obj(sort_param, @items)
    @items = @items.page(params[:page]).per(5)
  end

  def new
    @item = Item.new
  end

  def show; end

  def create
    @item = Item.new(item_params)

    if @item.valid?
      create_item
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @item.category_id = @item.category.id
  end

  def update
    @category = @item.category
    if @item.update(item_params)
      check_user('updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if !@item.user_id?
      redirect_to items_path, flash: { notice: 'Item was successfully deleted.' } if @item.destroy
    else
      redirect_to items_path, flash: { alert: 'We can not delete this item as item is allocated to a user.' }
    end
  end

  def search
    @items = search_obj(params, Item)
    fetch_item_of_employee
    @items = @items.page(params[:page]).per(5)
  end

  def clear_filter
    session[:category_id] = nil
    session[:brand_id] = nil
    session[:status] = nil
    @items = search_obj(params, Item)
    fetch_item_of_employee
    @items = @items.page(params[:page]).per(5)
  end

  private

  def fetch_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :brand_id, :category_id, :user_id, :status, :notes, documents: [])
  end
end

app/helpers/items_helper.rb
# frozen_string_literal: true

# this is the items helper
module ItemsHelper
  def create_item
    category = @item.category
    if category.present? && category.items.count < category.total_items
      @item.uid = generate_unique_id
      @item.save
      check_user('created')
    else
      flash.now[:alert] = "Cannot create new item. We don't need more item in #{@item.category.name} category."
      render :new
    end
  end

  def send_notification
    category = @item.category
    item_count = category.count_allocated_items
    buffer_quantity = category.buffer_quantity + category.required_quantity - category.expected_buffer
    msg = "In #{category.name.capitalize} category, the number of items
           is below the expected buffer quantity by #{item_count - buffer_quantity}."
    return unless item_count > buffer_quantity

    sent_notification_to_admin(category.priority, msg)
  end

  def sent_notification_to_admin(priority_msg, msg)
    User.get_admins.each do |admin|
      @notifications = Notification.create(recipient: admin, priority: priority_msg, message: msg)
    end
    ActionCable.server.broadcast('AdminChannel', { notification: @notifications })
  end

  def fetch_item_of_employee
    return if authenticate_user

    @items = @items.where(user_id: current_user.id)
  end

  def check_user(action)
    if @item.user_id.present?
      send_notification
      redirect_to @item, flash: { notice: "#{@item.category.name} successfully allocated to #{@item.user.name}" }
    else
      flash_message = action == 'created' ? 'Item created successfully.' : 'Item updated successfully.'
      redirect_to @item, flash: { notice: flash_message }
    end
  end

  def check_show
    return if authenticate_user
    return unless @item.user_id != current_user.id

    render file: Rails.public_path.join('404.html'), status: :not_found, layout: false
  end

  def generate_unique_id
    loop do
      random_id = SecureRandom.random_number(10_000)
      return random_id if Item.find_by(id: random_id).nil?
    end
  end

  def back_btn
    session[:back] == 'user' ? user_path(@item.user) : items_path
  end
end

app/views/items/_filter.html.erb
<div class="dropdown">
  <button class="btn  btn-sm filter-drop" type="button" id="filterDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= image_tag "filter.png", class: "filter-icon", title: 'filter' %> Filter
  </button>
  <div class="dropdown-menu" aria-labelledby="filterDropdown">
    <%= form_tag(search_items_path, method: "get", class: "dropdown-item") do %>
      <div class="form-group">
        <%= label_tag :category_id, "Category:" %>
        <%= select_tag :category_id, options_for_select([["All", ""]] + Category.all.map { |category| [category.name, category.id] }, session[:category_id]), class: "form-control" %>
      </div>
      <div class="form-group">
        <%= label_tag :brand_id, "Brand:" %>
        <%= select_tag :brand_id, options_for_select([["All", ""]] + Brand.all.map { |brand| [brand.name, brand.id] }, session[:brand_id]), class: "form-control" %>
      </div>
      <div class="form-group">
        <%= label_tag :status, "Status:" %>
        <%= select_tag :status, options_for_select([["All", ""], ["Working", "true"], ["Not Working", "false"]], session[:status]), class: "form-control" %>
      </div>
      <%= hidden_field_tag :filter, true %>
      <%= submit_tag "Apply Filters", class: "btn btn-primary btn-sm mt-2" %>
    <% end %>
  </div>
</div>

app/views/items/_form.html.erb
<%= form_with model: item do |form| %>
  <div class="mx-auto col-6">
    <div>
      <%= form.label :name, class: 'form-label required'%>
      <%= form.text_field :name, class: 'form-control' %>
      <p class='text-danger'><%= show_errors(@item, :name) %></p>
    </div>
    <div>
      <%= form.label :brand_id, class: 'form-label required' %>
      <%= form.select :brand_id, options_for_select(Brand.all.map { |brand| [brand.name, brand.id] }, item.brand_id), { prompt: 'Select brand' }, { class: 'form-select' } %>
      <p class='text-danger'><%= show_errors(@item, :brand_id) %></p>
    </div>
    <div>
      <%= form.label :category_id, class: 'form-label required' %>
      <%= form.select :category_id, options_for_select(Category.all.map { |category| [category.name, category.id] }, item.category_id), { prompt: 'Select category' }, { class: 'form-select' } %>
      <p class='text-danger'><%= show_errors(@item, :category_id) %></p>
    </div>
    <div>
      <%= form.label :user_id, 'Employee', class: 'form-label' %>
      <%= form.select :user_id, options_for_select(User.get_employees.map { |user| [user.email, user.id] }.unshift(['No User', nil]), item.user_id), { prompt: 'Select Employee' }, { class: 'form-select' } %>
      <p class='text-danger'><%= show_errors(@item, :user_id) %></p>
    </div>
    <div>
      <%= form.label :notes, class: 'form-label' %>
      <%= form.text_area :notes, class: 'form-control'  %>      
    </div>
    <div>
      <%= form.label :status, class: 'form-label required' %>
      <%= form.select(:status, options_for_select([['working', true],['not working', false]], item.status), {}, class: 'form-select') %>
    </div>
    <div class="field mt-4">
      <%= form.label :documents %>
      <%= form.file_field :documents, multiple: true %>
      <p class='text-danger'><%= show_errors(@item, :documents) %></p>
    </div>
    <div class="d-flex justify-content-center">
      <%= form.submit class: 'btn add-btn mt-3' %>
    </div>
  </div>
<% end %>

app/views/items/_list.html.erb
<tr class="text-center" data-items-id=<%= item.id %>>
  <td><%=link_to "#{item.uid}",item_path(item), class: "btn text-primary" %></td>
  <td><%= item.name %></td>
  <td><%= item.brand.name %></td>
  <td><%= item.category.name %></td>
  <td>
    <div class="status-cell <%= item.status ? 'working' : 'not-working' %>">
      <%= item.status ? 'Working' : 'Not Working' %>
    </div>
  </td> 
  <td><%= item.created_at.strftime('%B %d, %Y at %H:%M') %></td> 
  <td>
    <%= show_link((item_path(item)))%>
    <% if authenticate_user %>
      <%= edit_link(edit_item_path(item)) %>
      <%= delete_link(item_path(item)) if !item.user %>
    <% end %>
  </td>
</tr>

app/views/items/edit.html.erb
<%= link_to 'Back', request.referer || root_path, class: 'btn btn-sm add-btn' %>
<h5 class="p-3 text-center">Edit Item Details</h5>
<%= render "form", item: @item %>

app/views/items/index.html.erb
<div class="container mt-4 mb-4 d-flex justify-content-center align-items-center">
  <%= render 'partials/search', search: search_items_path  %>
  <%= render 'filter' %>
  <% if authenticate_user %>
    <%= link_to new_item_path, class: 'btn add-btn btn-sm' do %>
      <i class="fa-solid fa-plus fa-lg" style="color: #026c6da;"></i>Add Item
    <% end %>
  <% end %>
</div>
<% if @items.length == 0 %>
  <h3 class="text-center mt-4">No items found</h3>
<% else %>
  <div class="table-responsive">
    <table class="table table-striped items-list">
      <%= render 'partials/items', sort: items_path %>
      <tbody class="entities-list">
        <% @items.each do |item| %>
          <%= render 'list', item: item %>
        <% end %>
      </tbody>
    </table>
  </div>  
<% end %>
<%= render 'partials/paginate', obj: @items %>

app/views/items/new.html.erb
<%= link_to 'Back', request.referer || root_path, class: 'btn btn-sm add-btn' %>
<h5 class="p-3 text-center">Add Item</h5>
<%= render "form", item: @item %>

app/views/items/search.html.erb
<div class="container mt-4 mb-4 d-flex justify-content-center align-items-center">
  <%= render 'partials/search', search: search_items_path  %>
  <%= render 'filter' %>
  <% if check_session %>
    <%= form_tag(search_items_path, method: "get", class: "clear-filter-form mt-2 ") do %>
      <div class="form-group">
        <%= submit_tag "Clear Filter", class: "btn btn-sm add-btn" %>
      </div>
      <%= hidden_field_tag :query, '' %>
      <%= hidden_field_tag :category_id, '' %>
      <%= hidden_field_tag :brand_id, '' %>
      <%= hidden_field_tag :status, '' %>
      <%= hidden_field_tag :filter, true %>
    <% end %>
  <% end %>
</div>

<% unless @items.nil? %>
  <% if @items.empty? %>
    <p class="text-center mt-4">No results found</p>
  <% else %>
    <span>Search results</span><hr/>
    <div class="table-responsive">
      <table class="table table-striped">
        <%= render 'partials/items', sort: search_items_path %>
        <tbody>
        <% @items.each do |item| %>
          <%= render 'list', item: item %>
        <% end %>
        </tbody>
      </table>
    </div>  
  <% end %>
<% end %>
<%= render 'partials/paginate', obj: @items %>

app/views/items/show.html.erb
<%= link_to 'Back', back_btn, class: 'btn btn-sm add-btn' %>
<h5 class="p-3 text-center">Item Details</h5>
<div class="col-lg-5 mt-4 m-auto w-30">
  <div class="card mb-4">
    <div class="card-body">
      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0">Id</p>
        </div>
        <div class="col-sm-9">
          <p class="text-muted mb-0"><%= @item.uid %></p>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0">Name</p>
        </div>
        <div class="col-sm-9">
          <p class="text-muted mb-0"><%= @item.name %></p>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0">Brand</p>
        </div>
        <div class="col-sm-9">
          <p class="text-muted mb-0"><%= @item.brand.name %></p>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0">Category</p>
        </div>
        <div class="col-sm-9">
          <p class="text-muted mb-0"><%= @item.category.name %></p>
        </div>
      </div> 
      <hr> 
      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0">Status</p>
        </div>
        <div class="col-sm-9">
          <p class="text-muted mb-0"><%= @item.status ? 'Working' : 'Not Working' %></p>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0">Notes</p>
        </div>
        <div class="col-sm-9">
          <p class="text-muted mb-0"><%= @item.notes? ? @item.notes : '-----'  %></p>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0">Employee</p>
        </div>
        <div class="col-sm-9">
          <p class="text-muted mb-0"><%= @item.user.present? ? @item.user&.email : '-----' %></p>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0">Files</p>
        </div>
        <div class="col-sm-9">
          <p class="text-muted mb-0">
            <% if @item.documents.attached? %>
              <% @item.documents.each do |document| %>
                <%= link_to document.filename, url_for(document), class: 'btn btn-primary btn-sm m-2', target: '_blank' %><br>
              <% end %>
            <% else %>
              No File
            <% end %>
          </p>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-md-4 m-auto">
          <p class="text-muted mb-0">
            <div>
              <% if authenticate_user %>
                <%= edit_link(edit_item_path(@item))%>
                <%= delete_link(item_path(@item))%>
              <% end %>
            </div>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  function goBack() {
    window.history.back();
  }
</script>