config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength

Rails.application.routes.draw do
  root 'sessions#new'
  get '/dashboard', to: 'homes#welcome'
  get '/profile', to: 'homes#profile'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  delete '/logout', to: 'sessions#destroy'
  get '/authenticate', to: 'sessions#authenticate'
  get '/categories/fetch', to: 'categories#fetch_data'
  patch '/notifications/mark_read', to: 'notification#mark_read'
  patch '/notifications/mark/:id', to: 'notification#mark', as: :notifications_mark

  resources :users do
    collection do
      get :search
    end
  end
  resources :brands do
    collection do
      get :search
    end
  end
  resources :categories do
    collection do
      get :search
      get :storage
    end
  end
  resources :issues, except: %i[destroy edit] do
    collection do
      get :search
    end
  end
  resources :items do
    collection do
      get :search
      post :clear_filter
    end
  end
  resources :notification
  match '*unmatched', to: 'application#not_found_method', via: :all,
                      constraints: lambda { |req|
                                     !req.path.match(%r{\A/rails/active_storage/})
                                   }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

# rubocop:enable Metrics/BlockLength

app/models/brand.rb
# frozen_string_literal: true

# this is the Brand model
class Brand < ApplicationRecord
  include Searchable
  has_many :items
  validates :name, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }

  settings do
    mappings dynamic: false do
      indexes :name, type: :text
    end
  end
  def self.index_data
    __elasticsearch__.create_index! force: true
    __elasticsearch__.import
  end

  def self.search_result(query)
    search({
             "query": {
               "query_string": {
                 "query": "*#{query}*",
                 "fields": ['name']
               }
             }
           })
  end
  index_data
end

app/controllers/brands_controller.rb
# frozen_string_literal: true

# this is the Brands controller
class BrandsController < ApplicationController
  before_action :current_user?
  before_action :admin?
  before_action :fetch_brand, only: %i[edit update destroy]
  def index
    session[:query] = nil
    @brands = Brand.all
    sort_param = params[:sort_by]
    @brands = sort_obj(sort_param, @brands)
    @brands = @brands.page(params[:page]).per(5)
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(brand_params)
    if @brand.save
      redirect_to brands_path, flash: { notice: 'Brand successfully created.' }
    else
      render :new
    end
  end

  def edit; end

  def update
    if @brand.update(brand_params)
      redirect_to brands_path, flash: { notice: 'Brand was successfully updated.' }
    else
      render 'edit'
    end
  end

  def search
    @brands = search_obj(params, Brand)
    @brands = @brands.page(params[:page]).per(5)
  end

  def destroy
    if !@brand.items.present?
      @brand.destroy
      redirect_to brands_path, flash: { notice: 'Brand was successfully deleted.' }
    else
      redirect_to brands_path, flash: { alert: "#{@brand.name} brand cannot be deleted.
                                        There are items in this brand." }
    end
  end

  private

  def fetch_brand
    @brand = Brand.find(params[:id])
  end

  def brand_params
    params.require(:brand).permit(:name)
  end
end

app/views/brands/_form.html.erb
<div class="container w-50">
<%= form_with model: brand do |form| %>
  <div class="form-group mb-2">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
    <p class='text-danger'><%= show_errors(@brand, :name) %></p>
  </div>
  <div>
    <%= form.submit class:'btn add-btn' %>
  </div>
<% end %>
</div>

app/views/brands/_list.html.erb
<tr class="text-center" data-brands-id="<%= brand.id %>">
  <td class="brand-name"><%= brand.name %></td>
  <td><%= brand.created_at.strftime('%B %d, %Y at %H:%M') %></td> 
  <td class="d-flex gap-2 justify-content-center">
    <%= edit_link(edit_brand_path(brand)) %>
    <%= delete_link(brand_path(brand)) %>
  </td>
</tr>

app/views/brands/edit.html.erb
  <div class="container">
    <%= link_to 'Back', request.referer || root_path, class: 'btn btn-sm add-btn' %>
    <h5 class="p-3 text-center">Edit Brand Details</h5>
    <%= render "form", brand: @brand %>
  </div>

app/views/brands/index.html.erb
<div class="container mt-4 mb-4 d-flex justify-content-center align-items-center">
  <%= render 'partials/search', search_type: "Brands", search: search_brands_path %>
  <%= link_to  new_brand_path, class: 'btn add-btn btn-sm' do %>
    <i class="fa-solid fa-plus fa-lg" style="color: #026c6da;"></i>Add Brand
  <% end %>
</div>
<div class="col-lg-3 w-100 m-auto">
  <% if @brands.length == 0 %>
    <h3 class="text-center mt-4">No brand found</h3>
  <% else %>
    <table class="table table-striped">
      <%= render 'partials/brands', sort: brands_path %>
      <tbody class="entities-list" id="brands-list"> 
        <% @brands.each do |brand| %>
          <%= render 'list', brand: brand %>
        <% end %>
      </tbody>
    </table>
  <% end %>  
</div>
<%= render 'partials/paginate', obj: @brands %>

app/views/brands/new.html.erb
<div class="container">
  <%= link_to 'Back', request.referer || root_path, class: 'btn btn-sm add-btn' %>
  <h5 class="p-3 text-center">Add Brand Details</h5>
  <%= render "form", brand: @brand %>
</div>

app/views/brands/search.html.erb
<div class="container mt-4 mb-4 d-flex justify-content-center align-items-center">
  <%= render 'partials/search', search_type: "Brands", search: search_brands_path %>
</div>
<% unless @brands.nil? %>
  <% if @brands.empty? %>
    <p class="text-center mt-4">No results found</p>
  <% else %>
    <span>Search results</span><hr/>
    <div class="col-lg-3 w-100 m-auto">
    <table class="table table-striped">
      <%= render 'partials/brands', sort: search_brands_path %>
      <tbody>
        <% @brands.each do |brand| %>
          <%= render 'list', brand: brand %>
        <% end %>
      </tbody>
    </table>
    </div>
  <% end %>
<% end %>
<%= render 'partials/paginate', obj: @brands %>