config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength

Rails.application.routes.draw do
  root 'sessions#new'
  get '/dashboard', to: 'homes#welcome'
  get '/profile', to: 'homes#profile'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  delete '/logout', to: 'sessions#destroy'
  get '/authenticate', to: 'sessions#authenticate'
  get '/categories/fetch', to: 'categories#fetch_data'
  patch '/notifications/mark_read', to: 'notification#mark_read'
  patch '/notifications/mark/:id', to: 'notification#mark', as: :notifications_mark

  resources :users do
    collection do
      get :search
    end
  end
  resources :brands do
    collection do
      get :search
    end
  end
  resources :categories do
    collection do
      get :search
      get :storage
    end
  end
  resources :issues, except: %i[destroy edit] do
    collection do
      get :search
    end
  end
  resources :items do
    collection do
      get :search
      post :clear_filter
    end
  end
  resources :notification
  match '*unmatched', to: 'application#not_found_method', via: :all,
                      constraints: lambda { |req|
                                     !req.path.match(%r{\A/rails/active_storage/})
                                   }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

# rubocop:enable Metrics/BlockLength

app/models/category.rb
# frozen_string_literal: true

# this is the Category model
class Category < ApplicationRecord
  include Searchable
  enum priority: { low: 'low', medium: 'medium', high: 'high' }
  has_many :items

  validates :name, presence: { message: 'Please write the name of the category' }, length: { maximum: 50 },
                   uniqueness: { case_sensitive: false }
  validates :required_quantity, presence: { message: 'Please write the number of required quantity' },
                                numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :buffer_quantity, presence: { message: 'Please write the number of buffer quantity' },
                              numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :expected_buffer, presence: { message: 'Please write the number of expected buffer' },
                              numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :priority, presence: { message: 'Please select the priority' }
  validate  :validate_expected_buffer
  validate  :validate_required_quantity, on: :update
  validate  :validate_buffer_quantity, on: :update

  settings do
    mappings dynamic: false do
      indexes :name, type: :text
      indexes :required_quantity, type: :keyword
      indexes :buffer_quantity, type: :keyword
    end
  end

  def validate_expected_buffer
    return if expected_buffer.blank? || buffer_quantity.blank? || expected_buffer <= buffer_quantity

    errors.add(:expected_buffer, 'Expected buffer should be less than or equal to buffer quantity in this category')
  end

  def validate_required_quantity
    @category = Category.find(id)
    return if required_quantity.blank? || required_quantity >= items.count - @category.buffer_quantity

    errors.add(:required_quantity, 'Required quantity should be greater than or equal to total items in this category')
  end

  def validate_buffer_quantity
    return if buffer_quantity.blank? || buffer_quantity >= items.count - @category.required_quantity

    errors.add(:buffer_quantity, 'Buffer quantity should be greater than or equal to total items in this category')
  end

  def self.index_data
    __elasticsearch__.create_index! force: true
    __elasticsearch__.import
  end

  # rubocop:disable Metrics/MethodLength

  def self.search_result(query)
    search({
             "query": {
               "bool": {
                 "should": [
                   {
                     "query_string": {
                       "query": "*#{query}*",
                       "fields": ['name'],
                       "default_operator": 'AND'
                     }
                   },
                   {
                     "multi_match": {
                       "query": query,
                       "fields": %w[required_quantity buffer_quantity],
                       "operator": 'or'
                     }
                   }
                 ]
               }
             }
           })
  end
  # rubocop:enable Metrics/MethodLength

  def count_allocated_items
    items.where.not(user_id: nil).count
  end

  def total_items
    required_quantity + buffer_quantity
  end

  def storage
    required_quantity + buffer_quantity - count_allocated_items
  end
  index_data
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

# this is the Categories controller
class CategoriesController < ApplicationController
  before_action :current_user?
  before_action :admin?
  before_action :fetch_category, only: %i[edit update destroy]
  def index
    session[:query] = nil
    @categories = Category.all
    sort_param = params[:sort_by]
    @categories = sort_obj(sort_param, @categories)
    @categories = @categories.page(params[:page]).per(5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path, flash: { notice: 'Category successfully created.' }
    else
      render :new
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      redirect_to categories_path, flash: { notice: 'Category successfully updated.' }
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if !@category.items.present?
      @category.destroy
      redirect_to categories_path, flash: { notice: 'Category was successfully deleted.' }
    else
      redirect_to categories_path, flash: { alert: "#{@category.name} category cannot be deleted.
                                                    There are items in this category." }
    end
  end

  def storage
    @categories = Category.all
  end

  def search
    @categories = search_obj(params, Category)
    @categories = @categories.page(params[:page]).per(5)
  end

  def fetch_data
    category = Category.find(params[:category_id])
    storage = category.storage
    render json: { storage: }
  end

  private

  def fetch_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :required_quantity, :buffer_quantity, :expected_buffer, :priority)
  end
end

app/views/categories/_filter.html.erb
<div class="dropdown">
  <button class="btn  btn-sm filter-drop" type="button" id="filterDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= image_tag "filter.png", class: "filter-icon", title: 'filter' %> Filter
  </button>
  <div class="dropdown-menu" aria-labelledby="filterDropdown">
    <%= form_tag(search_categories_path, method: "get", class: "dropdown-item") do %>
      <div class="form-group">
        <%= label_tag :priority, "Priority:" %>
        <%= select_tag :priority, options_for_select([["All", ""], ["High", "high"], ["Medium", "medium"], ["Low","low"]], session[:priority]), class: "form-control" %>
      </div>    
      <%= hidden_field_tag :filter, true %>
      <%= submit_tag "Apply Filters", class: "btn btn-primary btn-sm mt-2" %>
    <% end %>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with model: category do |form| %>
  <div class="mx-auto col-md-6">
    <div> 
      <%= form.label :name, class: 'form-label required' %>
      <%= form.text_field :name, class: 'form-control' %>
      <p class='text-danger'><%= show_errors(@category, :name) %></p>
    </div>
    <div>
      <%= form.label :required_quantity, class: 'form-label required' %>
      <%= form.text_field :required_quantity , class: 'form-control'%>
      <p class='text-danger'><%= show_errors(@category, :required_quantity) %></p> 
    </div>
    <div>
      <%= form.label :buffer_quantity, class: 'form-label required' %>
      <%= form.text_field :buffer_quantity, class: 'form-control' %>
      <p class='text-danger'><%= show_errors(@category, :buffer_quantity) %></p> 
    </div>
    <div>
      <%= form.label :expected_buffer, class: 'form-label required' %>
      <%= form.text_field :expected_buffer, class: 'form-control' %>
      <p class='text-danger'><%= show_errors(@category, :expected_buffer) %></p> 
    </div>
    <div>
      <%= form.label :priority, class: 'form-label required' %>
      <%= form.select :priority, options_for_select(Category.priorities.keys, category.priority), { prompt: 'Select priority' }, { class: 'form-select mb-3' } %>
      <p class='text-danger'><%= show_errors(@category, :priority) %></p> 
    </div>
    <div class="d-flex justify-content-center">
      <%= form.submit class: 'btn add-btn mt-4' %>
    </div>
  </div>
<% end %>

app/views/categories/_list.html.erb
<tr class="text-center" data-categories-id=<%= category.id %>> 
  <td><%= category.name %></td>
  <td><%= category.required_quantity %></td>
  <td><%= category.buffer_quantity   %></td>
  <td><%= category.expected_buffer   %></td>
  <td>
    <div class="<%= category.priority %>">
      <%= category.priority.capitalize %>
    </div>
  </td>
  <td><%= category.created_at.strftime('%B %d, %Y at %H:%M') %></td> 
  <td class="d-flex gap-2 justify-content-center">
    <%= edit_link(edit_category_path(category)) %>
    <%= delete_link(category_path(category)) %>
  </td>
</tr>

app/views/categories/edit.html.erb
  <div class="container">
    <%= link_to 'Back', request.referer || root_path, class: 'btn btn-sm add-btn' %>
    <h5 class="p-3 text-center">Edit Category Details</h5>
    <%= render "form", category: @category %>
  </div>

app/views/categories/index.html.erb
<div class="container mt-4 mb-4 d-flex justify-content-center align-items-center">
  <%= render 'partials/search', search: search_categories_path %>
  <%= render 'filter', filter: categories_path %>
  <%= link_to  new_category_path, class: 'btn add-btn btn-sm' do %>
    <i class="fa-solid fa-plus fa-lg" style="color: #026c6da;"></i>Add Category
  <% end %>
</div>
<div>
  <% if @categories.length == 0 %>
    <h3 class="text-center mt-4">No category found</h3>
  <% else %>
  <div class="table-responsive">
    <table class="table table-striped categories-list">
      <%= render 'partials/categories', sort: categories_path %>
      <tbody class="entities-list">
        <% @categories.each do |category| %>
          <%= render 'list', category: category %>
        <% end %>
      </tbody>
    </table>
  </div>
  <% end %>
</div>
<%= render 'partials/paginate', obj: @categories %>

app/views/categories/new.html.erb
  <div class="container">
    <%= link_to 'Back', request.referer || root_path, class: 'btn btn-sm add-btn' %>
    <h5 class="p-3 text-center">Add Category</h5>
    <%= render "form", category: @category %>
  </div>

app/views/categories/search.html.erb
<div class="container mt-4 mb-4 d-flex justify-content-center align-items-center">
  <%= render 'partials/search', search: search_categories_path  %>
  <%= render 'filter', filter: search_categories_path %>
  <% if check_session %>
    <%= form_tag(search_categories_path, method: "get", class: "clear-filter-form mt-2") do %>
      <div class="form-group">
        <%= submit_tag "Clear Filter", class: "btn btn-sm add-btn" %>
      </div>
      <%= hidden_field_tag :query, '' %>
      <%= hidden_field_tag :priority, '' %>
      <%= hidden_field_tag :filter, true %>
    <% end %>
  <% end %>
</div>
<% unless @categories.nil? %>
  <% if @categories.empty? %>
    <p class="text-center mt-4">No results found</p>
  <% else %>
    <span>Search results</span><hr/>
    <div class="table-responsive">
      <table class="table table-striped t-over">
        <%= render 'partials/categories', sort: search_categories_path %>
        <tbody>
          <% @categories.each do |category| %>
            <%= render 'list', category: category %>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
<% end %>
<%= render 'partials/paginate', obj: @categories %>

app/views/categories/storage.html.erb
<%= javascript_include_tag 'storage' %>
<p class="text-lg mt-2">Storage</p><hr/>
<%= form_tag('/fetch_data', remote: true) do %>
  <%= select_tag(:option, options_for_select(@categories.map { |category| [category.name, category.id] }), prompt: 'Select category',class:'form-select w-50 m-auto', id: 'category-select') %>
<% end %>
<div class="col-md-6 col-lg-3 m-auto mt-4">
  <div class="card">
    <div class="card-body h-100">
      <p class="card-title">Remaning quantity in storage</p>
      <div id="result-container" class= "text-dark">
      </div>
    </div>
  </div>
</div